# docker-compose.yml
version: "3.8"

services:
  mongo:
    build: .
    container_name: my-mongo
    ports:
      - "27017:27017"
    env_file:
      - /etc/profile.d/chem-eng.sh
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
